name: CD

on: 
  push:
    branches:    
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install
      run: npm i
    - name: Build 
      run: gulp
    - name: Bundle
      run: mkdir ./out && mkdir ./out/food && mv dist/js ./out/food && mv dist/css ./out/food && mv dist/index.html ./out/food && mv dist/icons ./out/food && mv dist/img ./out/food
      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.DEPLOY_TOKEN }}
        external_repository: lisperata/lisperata.github.io
        publish_dir: ./out
        publish_branch: master
        keep_files: true